apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-09-12T09:32:58Z
  labels:
    run: hello
  name: hw
  namespace: default
  resourceVersion: "787498"
  selfLink: /api/v1/namespaces/default/services/hw
  uid: d5b1a8cc-b66e-11e8-a7c5-de66145c8f61
spec:
  clusterIP: 10.103.70.246
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30180
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: hello
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
