apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  labels:
    app: wp
spec:
  selector:
    matchLabels:
      app: wp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wp-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: wp
  labels:
    app: wp
spec:
 ports:
 - name: http
   port: 80
   targetPort: 80
   protocol: TCP
  selector:
    app: wp
    tier: frontend
 type: NodePort
